name: pdfchem
dependencies:
  - python=3.10
  - pip
  - numpy>=1.25
  - h5py>=3.9.0
  - matplotlib>=3.7.2
  - scipy>=1.10
  - astropy
  - plotly=5.24
  - pandas
  - conda-forge::ipython>=8.4.0
  - conda-forge::python-kaleido
  - conda-forge::python-ternary
  - conda-forge::aplpy
