name: pdfchem
dependencies:
  - python=3.10
  - pip
  - numpy>=1.25
  - h5py>=3.9.0
  - matplotlib>=3.7.2
  - scipy>=1.10
  - astropy
  - plotly
  - pandas
  - conda-forge::mercury
  - conda-forge::python-kaleido
  - conda-forge::python-ternary
